language: java

install:
  - ./gradlew -version

before_script:
  - ./gradlew clean assemble

jobs:
  include:
    - stage: test
      os: osx
      jdk: openjdk8
      script:
        - ./gradlew check --parallel

    - stage: test
      jdk: openjdk8
      script:
        - ./gradlew check --parallel

#    - stage: test
#      jdk: openjdk14
#      script:
#        - ./gradlew check

    - stage: test
      os: osx
      jdk: openjdk8
      script:
        - ./gradlew check --no-parallel

    - stage: test
      jdk: openjdk8
      script:
        - ./gradlew check --no-parallel

#    - stage: test
#      jdk: openjdk14
#      script:
#        - ./gradlew check --no-parallel
